### ISSUE TITLE
Call to undefined function Spatie\LaravelPackageTools\now()  

### ISSUE THREAD

**Issue by oulfr** [spatie/laravel-package-tools#16]
With PHP8 and lumen 8:

In PackageServiceProvider.php line 56:
                                                               
  Call to undefined function Spatie\LaravelPackageTools\now()

**Comment by freekmurze** [comment]
We don't support Lumen for this package.

**Comment by oulfr** [comment]
This is not a lumen error but php problem, there is no function now() in php 8

**Comment by freekmurze** [comment]
Laravel applications have `now()` by default.
