### ISSUE TITLE
Call to undefined method Spatie\LaravelPackageTools\Package::hasRoutes()

### ISSUE THREAD

**Issue by narcisonunez** [spatie/laravel-package-tools#20]
Hello,

I'm having some issues with my tests that are passing just in `P8 - L8.* - prefer-stable - ubuntu-latest` but failing in my other combinations.[`P8 - L7.* - prefer-lowest - ubuntu-latest`, `P8 - L7.* - prefer-stable - ubuntu-latest`, `P8 - L8.* - prefer-stable - ubuntu-latest`].

All my test are failing with the message: `Call to undefined method Spatie\LaravelPackageTools\Package::hasRoutes()`.

Do you have any Idea why?

Current setup: (Locally test are green)

Mac -> Catalina
php 7.4
composer 1

**Comment by freekmurze** [comment]
I cannot seem to reproduce this, and our tests are running fine.

I welcome a PR that fixes the problem for you.

**Comment by narcisonunez** [comment]
@freekmurze I already found the issue. 

Issue:

When you install the dependencies using `composer update --prefer-lowest` that will install `"spatie/laravel-package-tools": "^1.1"` that doesn't have hasRoute/hasRoutes methods. Also, will use the package name to register the views instead of the short name using `$this->package->shortPackageName()` and this one doesn't exists in the new version of the package.


To test this, after adding this in the Provider everything works.

```php
// Remove the hasViews call from package
$this->loadViewsFrom($this->package->basePath('/../resources/views'), 'scripts'); // hardcoded name to use the short version as the last version.

if (method_exists($package, 'hasRoute')) {
    $package->hasRoute('web');
} else {
    $this->loadRoutesFrom("{$this->package->basePath('/../routes/')}web.php");
}
```

Maybe you should update the `package-skeleton-laravel` to use a recent version of `"spatie/laravel-package-tools"`

**Comment by freekmurze** [comment]
Thanks for having investigated this.

> Maybe you should update the package-skeleton-laravel to use "spatie/laravel-package-tools": "^1.4.3"

Feel free to send a PR that requires the latest version.
