### ISSUE TITLE
Laravel 8 Support Dropped

### ISSUE THREAD

**Issue by Sammyjo20** [spatie/laravel-package-tools#68]
Hey there 👋 

I noticed that in tag v1.13, Laravel 8 support was dropped, but this doesn't follow semantic versioning, was this intentional or should there be a tag for v2.0 for Laravel 9 and v1.13 for Laravel 8?

Many thanks!

**Comment by freekmurze** [comment]
Dropping support for a major version is ok for semantic versioning. Composer will not pull in a version of laravel-package-tools that doesn't work your old Laravel 8 app

**Comment by Sammyjo20** [comment]
I did not know that, thanks!

**Comment by sammyaxe** [comment]
I wish there was backwards compatibility for Laravel 8, I'm using Sage (Laravel container) and it has not released support for Laravel 9, and this prevents me from installing `spatie/laravel-newsletter` will see if I can fallback to older tag
